/*
 * styles.cpp - Estilos do aplicativo LIBERTY
 */

#include "styles.h"
#include <QStringBuilder>

namespace Liberty {
namespace Styles {

QString getMainStyle() {
    return QString(
        "/* Global */"
        "QWidget {"
        "    background: %1;"
        "    color: %2;"
        "    font-family: 'Inter', 'Segoe UI', sans-serif;"
        "}"
        ""
        "/* Buttons */"
        "QPushButton {"
        "    background: %3;"
        "    border: 2px solid %4;"
        "    border-radius: 8px;"
        "    padding: 10px 20px;"
        "    color: %2;"
        "    font-size: 14px;"
        "}"
        ""
        "QPushButton:hover {"
        "    background: %4;"
        "    border-color: %5;"
        "}"
        ""
        "QPushButton:pressed {"
        "    background: %5;"
        "    color: %1;"
        "}"
        ""
        "/* Primary Button */"
        "QPushButton#primary_btn {"
        "    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,"
        "        stop:0 %5, stop:1 %6);"
        "    border: none;"
        "    color: %1;"
        "    font-weight: bold;"
        "}"
        ""
        "QPushButton#primary_btn:hover {"
        "    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,"
        "        stop:0 #FFFF33, stop:1 %5);"
        "}"
        ""
        "/* Line Edit */"
        "QLineEdit {"
        "    background: %3;"
        "    border: 2px solid %4;"
        "    border-radius: 8px;"
        "    padding: 12px 16px;"
        "    color: %2;"
        "    font-size: 14px;"
        "}"
        ""
        "QLineEdit:focus {"
        "    border-color: %5;"
        "}"
        ""
        "QLineEdit::placeholder {"
        "    color: %7;"
        "}"
        ""
        "/* Scrollbar */"
        "QScrollBar:vertical {"
        "    background: %3;"
        "    width: 6px;"
        "    border-radius: 3px;"
        "}"
        ""
        "QScrollBar::handle:vertical {"
        "    background: %5;"
        "    border-radius: 3px;"
        "    min-height: 20px;"
        "}"
        ""
        "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {"
        "    height: 0px;"
        "}"
        ""
        "/* Frame */"
        "QFrame {"
        "    background: transparent;"
        "}"
        ""
        "QFrame#divider {"
        "    background: %4;"
        "}"
    ).arg(COLOR_BLACK).arg(COLOR_WHITE).arg(COLOR_BLACK_LIGHT).arg(COLOR_BLACK_LIGHTER)
     .arg(COLOR_YELLOW).arg(COLOR_YELLOW_DARK).arg(COLOR_GRAY);
}

QString getSplashStyle() {
    return getMainStyle() % QString(
        "/* Splash Container */"
        "QFrame#splash_container {"
        "    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,"
        "        stop:0 %1, stop:1 %2);"
        "    border-radius: 20px;"
        "    border: 1px solid %3;"
        "}"
        ""
        "QLabel#splash_title {"
        "    font-size: 42px;"
        "    font-weight: bold;"
        "    color: %4;"
        "}"
        ""
        "QLabel#splash_subtitle {"
        "    font-size: 16px;"
        "    color: %5;"
        "}"
        ""
        "QLabel#status_label {"
        "    font-size: 12px;"
        "    color: %6;"
        "}"
        ""
        "QFrame#progress_frame {"
        "    background: %7;"
        "    border-radius: 2px;"
        "}"
        ""
        "QFrame#progress_bar {"
        "    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,"
        "        stop:0 %4, stop:1 %8);"
        "    border-radius: 2px;"
        "}"
    ).arg(COLOR_BLACK).arg(COLOR_BLACK_SOFT).arg(COLOR_BLACK_LIGHTER).arg(COLOR_YELLOW)
     .arg(COLOR_GRAY).arg(COLOR_GRAY_DARK).arg(COLOR_BLACK_LIGHT).arg(COLOR_YELLOW_DARK);
}

QString getLoginStyle() {
    return getMainStyle() % QString(
        "/* Login Window */"
        "QFrame#globe_panel {"
        "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,"
        "        stop:0 %1, stop:1 %2);"
        "    border-right: 1px solid %3;"
        "}"
        ""
        "QLabel#globe_title {"
        "    font-size: 28px;"
        "    font-weight: bold;"
        "    color: %4;"
        "}"
        ""
        "QLabel#globe_subtitle {"
        "    font-size: 14px;"
        "    color: %5;"
        "}"
        ""
        "QLabel#login_title {"
        "    font-size: 32px;"
        "    font-weight: bold;"
        "    color: %6;"
        "}"
        ""
        "QLabel#login_subtitle {"
        "    font-size: 14px;"
        "    color: %5;"
        "}"
        ""
        "QLabel#security_info {"
        "    font-size: 13px;"
        "    color: %7;"
        "}"
        ""
        "QPushButton#login_btn {"
        "    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,"
        "        stop:0 %4, stop:1 %8);"
        "    border: none;"
        "    border-radius: 8px;"
        "    font-size: 15px;"
        "    font-weight: bold;"
        "    color: %2;"
        "}"
        ""
        "QPushButton#login_btn:hover {"
        "    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,"
        "        stop:0 #FFFF33, stop:1 %4);"
        "}"
        ""
        "QPushButton#register_btn {"
        "    background: transparent;"
        "    border: 2px solid %4;"
        "    border-radius: 8px;"
        "    font-size: 14px;"
        "    color: %4;"
        "}"
        ""
        "QPushButton#register_btn:hover {"
        "    background: rgba(255, 255, 0, 0.1);"
        "}"
        ""
        "QFrame#divider_line {"
        "    background: %3;"
        "    max-height: 1px;"
        "}"
        ""
        "QLabel#or_label {"
        "    color: %7;"
        "    font-size: 12px;"
        "}"
        ""
        "QLabel#version_label {"
        "    font-size: 11px;"
        "    color: #444444;"
        "}"
    ).arg(COLOR_BLACK_SOFT).arg(COLOR_BLACK).arg(COLOR_BLACK_LIGHTER).arg(COLOR_YELLOW)
     .arg(COLOR_GRAY).arg(COLOR_WHITE).arg(COLOR_GRAY_DARK).arg(COLOR_YELLOW_DARK);
}

QString getMainWindowStyle() {
    return getMainStyle() % QString(
        "/* Server Sidebar */"
        "QFrame#server_sidebar {"
        "    background: %1;"
        "    border-right: 1px solid %2;"
        "    max-width: 72px;"
        "}"
        ""
        "QPushButton#server_btn {"
        "    background: %3;"
        "    border: none;"
        "    border-radius: 24px;"
        "    font-size: 18px;"
        "    font-weight: bold;"
        "    color: %4;"
        "}"
        ""
        "QPushButton#server_btn:hover {"
        "    border-radius: 12px;"
        "    background: %5;"
        "    color: %6;"
        "}"
        ""
        "QPushButton#server_btn_home {"
        "    background: %3;"
        "    border: 2px solid %5;"
        "    border-radius: 24px;"
        "    color: %5;"
        "}"
        ""
        "QPushButton#server_btn_home:hover {"
        "    background: %5;"
        "    color: %6;"
        "}"
        ""
        "QPushButton#server_btn_add {"
        "    background: transparent;"
        "    border: 2px dashed %5;"
        "    border-radius: 24px;"
        "    color: %5;"
        "    font-size: 24px;"
        "}"
        ""
        "QPushButton#server_btn_add:hover {"
        "    background: rgba(255, 255, 0, 0.1);"
        "}"
        ""
        "/* Channel Sidebar */"
        "QFrame#channel_sidebar {"
        "    background: %3;"
        "    border-right: 1px solid %2;"
        "    max-width: 240px;"
        "}"
        ""
        "QFrame#channel_header {"
        "    background: %1;"
        "    border-bottom: 1px solid %2;"
        "}"
        ""
        "QLabel#server_title {"
        "    font-size: 15px;"
        "    font-weight: bold;"
        "    color: %5;"
        "}"
        ""
        "/* User Panel */"
        "QFrame#user_panel {"
        "    background: %1;"
        "    border-top: 1px solid %2;"
        "}"
        ""
        "QLabel#user_avatar {"
        "    background: %5;"
        "    border-radius: 16px;"
        "    font-size: 12px;"
        "    font-weight: bold;"
        "    color: %6;"
        "}"
        ""
        "QLabel#user_name {"
        "    font-size: 13px;"
        "    font-weight: bold;"
        "    color: %7;"
        "}"
        ""
        "QLabel#user_status {"
        "    font-size: 11px;"
        "    color: %4;"
        "}"
        ""
        "/* Main Area */"
        "QFrame#main_header {"
        "    background: %6;"
        "    border-bottom: 1px solid %2;"
        "}"
        ""
        "QLabel#channel_name {"
        "    font-size: 16px;"
        "    font-weight: bold;"
        "    color: %7;"
        "}"
        ""
        "/* Messages */"
        "QLabel#message_avatar {"
        "    background: %5;"
        "    border-radius: 20px;"
        "    font-size: 14px;"
        "    font-weight: bold;"
        "    color: %6;"
        "}"
        ""
        "QLabel#message_author {"
        "    font-size: 14px;"
        "    font-weight: bold;"
        "    color: %5;"
        "}"
        ""
        "QLabel#message_time {"
        "    font-size: 11px;"
        "    color: %8;"
        "}"
        ""
        "QLabel#message_text {"
        "    font-size: 14px;"
        "    color: %7;"
        "}"
        ""
        "/* Crypto Bar */"
        "QFrame#crypto_bar {"
        "    background: rgba(255, 255, 0, 0.05);"
        "}"
        ""
        "QLabel#crypto_text {"
        "    font-size: 12px;"
        "    color: %4;"
        "}"
        ""
        "/* Message Input */"
        "QLineEdit#message_input {"
        "    background: %3;"
        "    border: none;"
        "    border-radius: 12px;"
        "    padding: 14px 16px;"
        "    font-size: 14px;"
        "    color: %7;"
        "}"
        ""
        "QPushButton#send_btn {"
        "    background: %5;"
        "    border: none;"
        "    border-radius: 20px;"
        "    color: %6;"
        "    font-size: 16px;"
        "}"
        ""
        "QPushButton#send_btn:hover {"
        "    background: #FFFF33;"
        "}"
        ""
        "/* Member Sidebar */"
        "QFrame#member_sidebar {"
        "    background: %3;"
        "    border-left: 1px solid %2;"
        "    max-width: 240px;"
        "}"
        ""
        "QLabel#member_header {"
        "    font-size: 12px;"
        "    font-weight: bold;"
        "    color: %4;"
        "    background: %1;"
        "}"
    ).arg(COLOR_BLACK_SOFT).arg(COLOR_BLACK_LIGHTER).arg(COLOR_BLACK_LIGHT).arg(COLOR_GRAY)
     .arg(COLOR_YELLOW).arg(COLOR_BLACK).arg(COLOR_WHITE).arg(COLOR_GRAY_DARK);
}

} // namespace Styles
} // namespace Liberty
